# Generated by Django 4.2.6 on 2023-10-25 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevmanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('email', models.EmailField(blank=True, default='', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=80, verbose_name='тема проекта')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='StudyingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(choices=[(datetime.time(10, 0), 'с 10:00 до 10:30'), (datetime.time(13, 0), 'с 13:00 до 13:30'), (datetime.time(13, 30), 'с 13:30 до 14:00'), (datetime.time(14, 0), 'с 14:00 до 14:30'), (datetime.time(14, 30), 'с 14:30 до 15:00'), (datetime.time(15, 0), 'с 15:00 до 15:30'), (datetime.time(15, 30), 'с 15:30 до 16:00'), (datetime.time(16, 0), 'с 16:00 до 16:30'), (datetime.time(16, 30), 'с 16:30 до 17:00')], verbose_name='Время начала созвонов')),
            ],
        ),
        migrations.CreateModel(
            name='Pm',
            fields=[
                ('devmanuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.devmanuser')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            bases=('registration.devmanuser',),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('newbie', 'новичок'), ('newbie+', 'новичок+'), ('junior', 'джун')], max_length=40, null=True, verbose_name='Роль')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.devmanuser')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.studyingtime')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название команды')),
                ('call_day', models.DateTimeField(verbose_name='День созвона')),
                ('call_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.studyingtime')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='registration.students', verbose_name='Ученики')),
                ('pmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.pm')),
            ],
        ),
    ]
